### ISSUE TITLE
Do you really want to use html as configuration file format?

### ISSUE THREAD

**Issue by dimorinny** [ussserrr/starmap-northern#1]
Let's format these html files to, for example, yaml?

**Comment by ussserrr** [comment]
@dimorinny HTML storing is a built-in feature of Astropy and also such data more human-readable and can be used separately from the app itself :)
![stars](https://user-images.githubusercontent.com/20915411/39406857-00230fea-4bc6-11e8-89dd-92f9dc323f38.png)
![const](https://user-images.githubusercontent.com/20915411/39406859-05fe305c-4bc6-11e8-8bb1-2184c7608631.png)
